@startuml
[*]->startup
startup --> measure_ph
measure_ph --> measure_ec : left_pressed 
measure_ph --> calibration_ph : up_pressed
measure_ph --> change_ph_range :down_pressed
measure_ec --> calibration_ec : up_pressed
measure_ec --> change_ec_range :down_pressed
measure_ec --> measure_ph : left_pressed

state calibration_ph{
    [*] -> set_first_sample_ph
    set_first_sample_ph --> set_second_sample_ph : center_pressed
    set_second_sample_ph --> measure_ph : center_pressed
}

state calibration_ec{
    [*] -> set_first_sample_ec
    set_first_sample_ec --> set_second_sample_ec : center_pressed
    set_second_sample_ec --> measure_ec : center_pressed
}

state change_ph_range{
    [*] -> set_ph_range
    set_ph_range --> measure_ph : center_pressed  
}

state change_ec_range{
    [*] -> set_ec_range
    set_ec_range --> measure_ec : center_pressed  
}

state measure_ph{
    [*] -> present_ph_data
    present_ph_data --> automation
    automation --> present_ph_data
}

state measure_ec{
    [*] -> present_ec_data
    present_ec_data --> automation
    automation --> present_ec_data
}

state automation{
    [*] -> check_ph_automation
    check_ph_automation --> fill_ph : ec_out_of_range
    check_ph_automation --> check_ec_automation : correct_ph
    check_ec_automation --> fill_ec : ph_out_of_range
    check_ec_automation --> [*] : correct_ec
    fill_ph --> [*]
    fill_ec --> [*]
}

@enduml